### ISSUE TITLE
Export/Import Wallets

### ISSUE THREAD

**Issue by PaulSnow** [FactomProject/WorkItems#416]
Pretty much what it says.  Need to be able to create an export of a wallet from FctWallet.  This can be a binary blob, but we do need to consider security of said blob.

Then we need to be able to import the blob.  Again a security needs to be considered.

Assigning first to Brian to set security expectations of these wallets.  Maybe we don't add passwords on exported wallets until after Milestone 1?

**Comment by carryforward** [comment]
hmm, passwords are protection against casual thefts, where a friends logs onto your computer.  if you are serious about security, then you would hold your factoids on an offline computer.  If we make it easy to import a wallet, then people can just import it when needed if worried about casual thefts in milestone 1.

I agree, wallet passwords can wait.

**Comment by hannemennah** [comment]
Brian and I sat down and had an extended discussion about this, and here is a synopsis of our thoughts on the matter:

There does not seem to be a clearly-identifiable use-case for this functionality. If someone wants to use the keys/addresses of one wallet, they can use the corresponding bolt.db file to do so... if they would rather use the keys/addresses of another, they can use that bold.db file instead. 

Because these two db files' deterministic key-seeds will be different, trying to mash the two seeds together into one wallet db file could significantly complicate matters and incur a great deal of extra overhead, maintenance, and development to mitigate resultant conflicts or confusion in the addresses used by the wallet. Once again, there doesn't seem to be a clear reason why someone would want to do this, either.

If someone did want to recover the addresses/keys from a particular seed (or seeds), that can be done with existing utilities and could, in the future, be done with more robust and intelligent tools that we (or others) build for the purpose. These keys can be imported normally into an existing wallet (though the ability to deterministically regenerate them would be missing, if they deleted the seed data after importing the keys). 

If the sole purpose of this functionality would be for security (granting the ability to create wallet information on one offline/secure machine, and then import it on a "hot" machine later), then this will essentially be moot after wallet encryption is possible, since encryption is a far superior solution for this sort of thing.

If, instead, the idea is to allow a user to use a new bolt.db file entirely, this can be done directly in the filesystem (back up or rename the existing bolt.db file used, and replace it with the new one that you would rather use). There's not much utility in creating a command or API call for this sort of thing. It might make sense to create a standalone tool to help with making this process more user-friendly, but this is certainly not something to overly worry about at this stage.

I will close this Work Item, and we can re-open it if we ever think of a compelling reason to.
