### ISSUE TITLE
minute markers in Factoid block

### ISSUE THREAD

**Issue by carryforward** [FactomProject/WorkItems#491]
there should be minute markers when minutes pass in the factoid blocks.

**Comment by PaulSnow** [comment]
I am thinking we should add 9 4 byte slots to the header to give the the divisions between the minutes as transaction indexes.  

This is because I either have to add a type byte to every transaction in the block (so I can tell a minute marker from a transaction) or I have to add a bogus transaction that marks the EOM position.  But either we don't have many transactions (so 36 bytes isn't a big deal).  Or we have many transactions.  If many, then a byte per transaction IS a big deal.  More interestingly, having purposely bogus transactions adds complexity to later validation and header entries avoids that.

**Comment by PaulSnow** [comment]
So the minute markers are managed in the header, but are written into the transaction list when marshaled.

All I do is write an "FF" between each minute ending.  "FFFF" would indicate an empty period.

When I unmarshal, I look for these indicators, and reconstitute the header.
