### ISSUE TITLE
admin block should have sha256 in dblock instead of sha512[:256]

### ISSUE THREAD

**Issue by carryforward** [FactomProject/WorkItems#584]
admin block 0 is 
`000000000000000000000000000000000000000000000000000000000000000A000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000`
and has a sha256 hash of 
4fb409d5369fad6aa7768dc620f11cd219f9b885956b631ad050962ca934052e
and a sha512[:256] of
0a9aa1efbe7d0e8d9c1d460d1c78e3e7b50f984e65a3f3ee7b73100a94189dbf.

Admin block 1 should have 0a9aa... as the previous block, which is correct.

Directory block 0 should have 4fb409... as the handle to the admin block.  instead it has 0a9aa...

**Comment by ThePiachu** [comment]
Turns out there were a few places that took it upon themselves to create the hash for the Admin Block. Made sure only Admin Block code generates the hash now.

Currently the Directory Block uses ABHash from Admin Block, which is Sha512Half. This keeps everything consistent really - are we sure we need to replace the Shaa512Half with Sha256 for Directory Block?

**Comment by carryforward** [comment]
"are we sure we need to replace the"

yes, the intent was to have the admin block protected by 2 different hashes.

**Comment by carryforward** [comment]
now to check it in development.  thank you Piachu

**Comment by carryforward** [comment]
good
