### ISSUE TITLE
walletapp: exporting a transaction to an already existing filename gives no feedback

### ISSUE THREAD

**Issue by drobertbaker** [FactomProject/WorkItems#781]
Does it overwrite the old transaction?
Does it not write the new transaction?
Is it doing what we want it to do?

Please give feedback to the user as to the result of the export action.

***edit***

I now see that a message IS displayed, but in the text window:

File Exists.  Overwrite? (Y/N): 

Someone working on the browser cannot see this message or respond to it. Please display it in the browser.

**Comment by hannemennah** [comment]
I've updated it so that it only saves to filenames that don't yet exist, and otherwise provides an error message that the file already exists. For right now, I don't think we should allow overwriting of existing files, because there's a chance of someone saving a transaction to a .go or .db file mistakenly and overwriting something they would rather not.

If we think it's a good idea, though, I can add a secondary prompt asking if you'd like to overwrite the file (if it exists). I just feel like that might be asking for trouble.

**Comment by drobertbaker** [comment]
OK, we agree with you. Good call!

On Wed, Oct 14, 2015 at 4:11 PM, Justin Hanneman <notifications@github.com>
wrote:

> Assigned #781 <https://github.com/FactomProject/WorkItems/issues/781> to
> @drobertbaker <https://github.com/drobertbaker>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FactomProject/WorkItems/issues/781#event-435731835>.
>



-- 
Thanks,
D. Robert Baker
Process Integration Manager, factom
drobertbaker@factom.org
