### ISSUE TITLE
walletapp: UITX empty transaction

### ISSUE THREAD

**Issue by drobertbaker** [FactomProject/WorkItems#790]
List Transaction includes UITX in the list, but Load Transaction To Form of UITX yields "No such transaction.".

**Comment by hannemennah** [comment]
Looks like it was just a problem of an inaccurate error message. The actual issue is that the transaction exists, it's just completely empty. [Fixed in this commit,](https://github.com/FactomProject/fctwallet/commit/3b7cbbdd77bbe25335e6314590b937f0b3b9871f) by updating the message to say that the transaction is empty (rather than nonexistent).

**Comment by drobertbaker** [comment]
OK
